name: Backend Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  PYTHON_VERSION: '3.10'

jobs:
  # note lint and test are run in parallel
  # build waits / needs both to be completed first
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install dependencies
        run: |
          pip install flake8
          pip install pipenv
          pipenv update
          pipenv install
          pipenv --rm
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
          pipenv run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
          pipenv run lint

      # then build with Docker and
      #  don't do anything else (ie do not push) as this is just to
      #  verify the Dockerfile and build is working correctly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
